[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
attesta = "Attesta11111111111111111111111111111111"

[programs.mainnet]
attesta = "Attesta11111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator.clone]
geyser = true

[test.validator.account]
[test.validator.account."spl_token::state::Mint"]
[test.validator.account."spl_token::state::Account"]
